### ISSUE TITLE
Give more illustration about the data

### ISSUE THREAD

**Issue by PhuDoTuong** [Lazer7/D3-Eye-Visualization#1]
Thank you for your amazing work.
Would you mind giving me the positions of the two cameras and light sources (if they exist)?
Thank you so much.

**Comment by Lazer7** [comment]
Hi @PhuDoTuong, I apologize we don't have the data for the two cameras or light sources. We do have XY camera data in the https://github.com/Lazer7/D3-Eye-Visualization/tree/master/Data GZD files if your interested in that data.

**Comment by PhuDoTuong** [comment]
Hello @Lazer7. Thank you so much.
